name: 03.Deploy to Netlify and Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Deploy React Frontend to Netlify
  deploy-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
        working-directory: modules/03.Continuous_Delivery/front-end

      - name: Build the React app
        run: npm run build
        working-directory: modules/03.Continuous_Delivery/front-end

      - name: Publish
        uses: netlify/actions/cli@master
        with:
            args: deploy --dir=modules/03.Continuous_Delivery/front-end/build --prod
        env:
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

#   Deploy Flask Backend to Render
  deploy-flask:
    runs-on: ubuntu-latest
    steps:
      - name: Flask Deployment
        run: echo "Render will automatically deploy once you connect from render dashboard"