name: 03.Deploy Flask to Render

on:
  push:
    branches:
      - main

jobs:
#   Deploy Flask Backend to Render
  deploy-flask:
    runs-on: ubuntu-latest
    steps:
      - name: Flask Deployment
        run: echo "Render will automatically deploy once you connect from render dashboard"