name: 03.Deploy Flask to Render

on:
  push:
    branches:
      - main

jobs:
  #   Deploy Flask Backend to Render
  deploy-flask:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deployment
        run: |
          curl --request POST \
               --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
               --header 'accept: application/json' \
               --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
               --header 'content-type: application/json'
