name: 03.Deploy Flask to Render

on:
  push:
    branches:
      - dev

jobs:
  deploy-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
        continue-on-error: false
        id: install-dependencies

      - name: Run Flake8 Linting
        run: flake8 .
        continue-on-error: false
        id: run-flake8

      - name: Trigger Render deployment
        run: |
          curl --request POST \
               --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
               --header 'accept: application/json' \
               --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
               --header 'content-type: application/json'
        continue-on-error: false
        id: deploy-render

      - name: Teams Notification
        if: always()  
        run: |
          status="${{ job.status }}"
          if [ "${status}" == "success" ]; then
            COLOR="#00FF00" # Green for success
          else
            COLOR="#FF0000" # Red for failure
          fi

          # Prepare the message for Teams
          curl -H 'Content-Type: application/json' \
               -d '{
                    "title": "Flask App Deployment Status",
                    "text": "Deployment to Render triggered by '${{ github.actor }}' on branch '${{ github.ref_name }}' has completed.",
                    "sections": [{
                      "activityTitle": "Deployment Status: '${{ job.status }}'",
                      "facts": [
                        {"name": "Deployed by", "value": "'${{ github.actor }}'"},
                        {"name": "Branch", "value": "'${{ github.ref_name }}'"},
                        {"name": "Commit Message", "value": "'${{ github.event.head_commit.message }}'"},
                        {"name": "Commit SHA", "value": "'${{ github.sha }}'"},
                        {"name": "Repository", "value": "'${{ github.repository }}'"},
                        {"name": "Job Status", "value": "'${{ job.status }}'"},
                        {"name": "Workflow Run ID", "value": "'${{ github.run_id }}'"},
                        {"name": "Workflow URL", "value": "'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'"} 
                      ]
                    }],
                    "themeColor": "'${COLOR}'"
                  }' \
               ${{ secrets.TEAMS_WEBHOOK_URL }}
